### PR TITLE
Dealing with localized web part gallery name

### PR DESCRIPTION
**Pull request by sknoche**
If the SP installation is using a different locale, the list "Web Part Gallery" does not exist.

### CODE REVIEW

**Comment by sknoche** [comment]
If the SP installation is using a different locale, the List "Web Part Gallery" does not exist.

**Comment by gunjandatta** [comment]
Thank you for submitting this pull request. I'll review the code today and make the update today or tomorrow.

**Comment by gunjandatta** [comment]
Instead of creating a new method, I updated it to use the getCatalog() method and am using the WebPartCatalog template type.

Thank you for pointing this out. I've been meaning to update this class, and will do so in the near future to help w/ the performance of the initial query.

v3.6.3 has this fix in it.

**Comment by sknoche** [comment]
Great ;)

**Pull request closed without merging**
